--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/ngeran/Wallpapers/astronaut-with-jellyfish-2560x1600_786654-mm-90.jpg"

-- Special
background="#0a0c12"
foreground="#a6bcc1"
cursor="#a6bcc1"

-- Colors
color0="#0a0c12"
color1="#533142"
color2="#31554F"
color3="#5A5B5A"
color4="#B05255"
color5="#38A65C"
color6="#B2A54C"
color7="#a6bcc1"
color8="#748387"
color9="#533142"
color10="#31554F"
color11="#5A5B5A"
color12="#B05255"
color13="#38A65C"
color14="#B2A54C"
color15="#a6bcc1"
